package com.awsBuilder.builder.cloudformation.service;

import com.awsBuilder.builder.cloudformation.model.CloudFormationResource;
import com.awsBuilder.builder.diagram.model.NodeDTO;
import com.awsBuilder.builder.diagram.model.ResourceGraph;
import org.springframework.stereotype.Component;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.representer.Representer;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Component
public class CloudFormationGenerator {
    
    private final CloudFormationTemplateRegistry registry;
    
    public CloudFormationGenerator(CloudFormationTemplateRegistry registry) {
        this.registry = registry;
    }
    
    public String generate(List<NodeDTO> orderedNodes, ResourceGraph graph, String region) {
        // Build the CloudFormation document structure
        Map<String, Object> document = new LinkedHashMap<>();
        
        // Add template format version
        document.put("AWSTemplateFormatVersion", "2010-09-09");
        
        // Add description
        document.put("Description", "Generated by AWS Builder");
        
        // Add parameters with region
        Map<String, Object> parameters = new LinkedHashMap<>();
        Map<String, Object> regionParam = new LinkedHashMap<>();
        regionParam.put("Type", "String");
        regionParam.put("Default", region);
        parameters.put("Region", regionParam);
        document.put("Parameters", parameters);
        
        // Build resources section by merging template fragments
        Map<String, Object> resources = new LinkedHashMap<>();
        
        for (NodeDTO node : orderedNodes) {
            // Get the template for this node type
            CloudFormationResource template = registry.getTemplate(node.getType());
            
            // Generate YAML fragment from template
            String yamlFragment = template.generate(node, graph);
            
            // Parse the YAML fragment back into a map
            Yaml yamlParser = new Yaml();
            Map<String, Object> fragmentMap = yamlParser.load(yamlFragment);
            
            // Merge fragment into resources
            if (fragmentMap != null) {
                resources.putAll(fragmentMap);
            }
        }
        
        document.put("Resources", resources);
        
        // Serialize to YAML with custom representer for !Ref tags
        DumperOptions opts = new DumperOptions();
        opts.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        opts.setPrettyFlow(true);
        
        Representer representer = new CloudFormationRepresenter();
        Yaml yaml = new Yaml(representer, opts);
        
        return yaml.dump(document);
    }
    
    /**
     * Custom Representer to emit strings starting with '!' as unquoted scalars.
     * This allows CloudFormation intrinsic functions like !Ref to be properly serialized.
     */
    private static class CloudFormationRepresenter extends Representer {
        public CloudFormationRepresenter() {
            super(new DumperOptions());
        }
        
        @Override
        protected org.yaml.snakeyaml.nodes.Node representScalar(org.yaml.snakeyaml.nodes.Tag tag, String value, DumperOptions.ScalarStyle style) {
            // If the value starts with '!', emit it as a plain scalar (unquoted)
            if (value != null && value.startsWith("!")) {
                return super.representScalar(tag, value, DumperOptions.ScalarStyle.PLAIN);
            }
            return super.representScalar(tag, value, style);
        }
    }
}
